// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Build script and C-ABI header generator for futharkiser.
//
// Generates:
//   - A C header file declaring the Futhark entry point signatures, suitable
//     for calling compiled GPU kernels from any language with C FFI support.
//   - A shell build script that invokes the Futhark compiler with the correct
//     backend flags and optional auto-tuning.

use anyhow::Result;
use std::path::Path;

use crate::abi::{KernelConfig, SOAC};
use crate::manifest::Manifest;

// ---------------------------------------------------------------------------
// C-ABI header generation
// ---------------------------------------------------------------------------

/// Generate a C header file declaring function prototypes for every kernel
/// entry point. The Futhark compiler produces these automatically, but having
/// a standalone header makes it easier to write FFI bindings from Zig, Rust,
/// or other languages without compiling the Futhark program first.
pub fn generate_c_header(manifest: &Manifest, kernels: &[KernelConfig]) -> Result<String> {
    let mut out = String::with_capacity(2048);
    let guard = manifest.project.name.to_uppercase().replace('-', "_");

    // Header preamble.
    out.push_str(&format!(
        "/* Auto-generated by futharkiser for project '{}' */\n",
        manifest.project.name
    ));
    out.push_str("/* SPDX-License-Identifier: PMPL-1.0-or-later */\n");
    out.push_str("/* Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk> */\n");
    out.push_str("/* DO NOT EDIT — regenerate with: futharkiser generate */\n\n");
    out.push_str(&format!("#ifndef {}_H\n", guard));
    out.push_str(&format!("#define {}_H\n\n", guard));
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n\n");

    // Opaque context type (Futhark runtime convention).
    out.push_str("/* Futhark runtime context (opaque — created by futhark_context_new) */\n");
    out.push_str("struct futhark_context;\n\n");

    // Generate a prototype for each kernel.
    for kernel in kernels {
        out.push_str(&generate_c_prototype(kernel));
        out.push('\n');
    }

    out.push_str(&format!("#endif /* {}_H */\n", guard));
    Ok(out)
}

/// Generate a C function prototype for a single kernel entry point.
///
/// Futhark's C API convention:
///   - All entry points take `struct futhark_context *ctx` as the first arg.
///   - Array arguments are passed as `struct futhark_{type}_1d *`.
///   - Scalar results are returned via out-pointer.
///   - Array results are returned via out-pointer to the opaque array type.
fn generate_c_prototype(kernel: &KernelConfig) -> String {
    let mut out = String::new();

    // Comment with the kernel description.
    if !kernel.description.is_empty() {
        out.push_str(&format!("/* {} */\n", kernel.description));
    }

    let out_c = kernel.output_type.c_type();
    let in_fut = kernel.input_type.futhark_name();
    let out_fut = kernel.output_type.futhark_name();

    match kernel.pattern {
        SOAC::Map => {
            // map: takes 1D array, returns 1D array of same length.
            out.push_str(&format!(
                "int futhark_entry_{name}(\n\
                 \x20   struct futhark_context *ctx,\n\
                 \x20   struct futhark_{out_fut}_1d **out,\n\
                 \x20   const struct futhark_{in_fut}_1d *xs);\n",
                name = kernel.name,
                in_fut = in_fut,
                out_fut = out_fut,
            ));
        }
        SOAC::Reduce => {
            // reduce: takes 1D array, returns scalar.
            out.push_str(&format!(
                "int futhark_entry_{name}(\n\
                 \x20   struct futhark_context *ctx,\n\
                 \x20   {out_c} *out,\n\
                 \x20   const struct futhark_{in_fut}_1d *xs);\n",
                name = kernel.name,
                out_c = out_c,
                in_fut = in_fut,
            ));
        }
        SOAC::Scan => {
            // scan: takes 1D array, returns 1D array of same length.
            out.push_str(&format!(
                "int futhark_entry_{name}(\n\
                 \x20   struct futhark_context *ctx,\n\
                 \x20   struct futhark_{out_fut}_1d **out,\n\
                 \x20   const struct futhark_{in_fut}_1d *xs);\n",
                name = kernel.name,
                in_fut = in_fut,
                out_fut = out_fut,
            ));
        }
        SOAC::Scatter => {
            // scatter: takes dest array, index array, values array; returns dest.
            out.push_str(&format!(
                "int futhark_entry_{name}(\n\
                 \x20   struct futhark_context *ctx,\n\
                 \x20   struct futhark_{out_fut}_1d **out,\n\
                 \x20   struct futhark_{out_fut}_1d *dest,\n\
                 \x20   const struct futhark_i64_1d *is,\n\
                 \x20   const struct futhark_{in_fut}_1d *vs);\n",
                name = kernel.name,
                in_fut = in_fut,
                out_fut = out_fut,
            ));
        }
        SOAC::Histogram => {
            // histogram: takes 1D array, returns 1D array of bin counts.
            out.push_str(&format!(
                "int futhark_entry_{name}(\n\
                 \x20   struct futhark_context *ctx,\n\
                 \x20   struct futhark_{out_fut}_1d **out,\n\
                 \x20   const struct futhark_{in_fut}_1d *xs);\n",
                name = kernel.name,
                in_fut = in_fut,
                out_fut = out_fut,
            ));
        }
    }

    out
}

// ---------------------------------------------------------------------------
// Build script generation
// ---------------------------------------------------------------------------

/// Generate a shell script that compiles the Futhark source with the configured
/// backend. The script is self-contained and can be run without futharkiser.
pub fn generate_build_script(manifest: &Manifest, fut_source_path: &Path) -> Result<String> {
    let mut out = String::with_capacity(1024);
    let backend = &manifest.gpu.backend;
    let source = fut_source_path
        .file_name()
        .map(|f| f.to_string_lossy().to_string())
        .unwrap_or_else(|| format!("{}.fut", manifest.project.name));

    out.push_str("#!/usr/bin/env bash\n");
    out.push_str("# Auto-generated by futharkiser — DO NOT EDIT\n");
    out.push_str("# SPDX-License-Identifier: PMPL-1.0-or-later\n");
    out.push_str(&format!(
        "# Build script for project '{}'\n\n",
        manifest.project.name
    ));
    out.push_str("set -euo pipefail\n\n");

    // Check that futhark is installed.
    out.push_str("if ! command -v futhark &> /dev/null; then\n");
    out.push_str("  echo \"Error: futhark compiler not found in PATH\" >&2\n");
    out.push_str("  echo \"Install from https://futhark-lang.org/\" >&2\n");
    out.push_str("  exit 1\n");
    out.push_str("fi\n\n");

    // Print version.
    out.push_str("echo \"Using $(futhark --version)\"\n\n");

    // Compile.
    out.push_str(&format!(
        "echo \"Compiling {} with backend '{}'\"\n",
        source, backend
    ));
    out.push_str(&format!("futhark {} {}\n\n", backend, source));

    // Optional auto-tuning.
    if manifest.gpu.tuning {
        out.push_str(&format!("echo \"Auto-tuning for backend '{}'\"\n", backend));
        out.push_str(&format!(
            "futhark autotune --backend={} {}\n\n",
            backend, source
        ));
    }

    out.push_str("echo \"Build complete.\"\n");

    Ok(out)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::FutharkType;
    use crate::manifest::{GpuConfig, ProjectConfig};

    fn test_manifest() -> Manifest {
        Manifest {
            project: ProjectConfig {
                name: "test-project".to_string(),
            },
            kernels: vec![],
            gpu: GpuConfig {
                backend: "opencl".to_string(),
                tuning: false,
            },
        }
    }

    fn make_kernel(
        name: &str,
        pattern: SOAC,
        in_ty: FutharkType,
        out_ty: FutharkType,
    ) -> KernelConfig {
        KernelConfig {
            name: name.to_string(),
            pattern,
            input_type: in_ty,
            output_type: out_ty,
            description: String::new(),
            operator: None,
            bins: None,
        }
    }

    #[test]
    fn test_c_header_structure() {
        let manifest = test_manifest();
        let kernels = vec![make_kernel(
            "blur",
            SOAC::Map,
            FutharkType::F32,
            FutharkType::F32,
        )];
        let header = generate_c_header(&manifest, &kernels).unwrap();
        assert!(header.contains("#ifndef TEST_PROJECT_H"));
        assert!(header.contains("#define TEST_PROJECT_H"));
        assert!(header.contains("#include <stdint.h>"));
        assert!(header.contains("futhark_entry_blur"));
        assert!(header.contains("futhark_f32_1d"));
    }

    #[test]
    fn test_c_header_reduce_returns_scalar() {
        let manifest = test_manifest();
        let mut kernel = make_kernel("sum", SOAC::Reduce, FutharkType::F64, FutharkType::F64);
        kernel.operator = Some("+".to_string());
        let header = generate_c_header(&manifest, &[kernel]).unwrap();
        assert!(header.contains("double *out"));
    }

    #[test]
    fn test_c_header_scatter_has_three_args() {
        let manifest = test_manifest();
        let kernel = make_kernel("write", SOAC::Scatter, FutharkType::F32, FutharkType::F32);
        let header = generate_c_header(&manifest, &[kernel]).unwrap();
        assert!(header.contains("dest"));
        assert!(header.contains("futhark_i64_1d *is"));
    }

    #[test]
    fn test_build_script_contains_backend() {
        let manifest = test_manifest();
        let script = generate_build_script(&manifest, Path::new("test-project.fut")).unwrap();
        assert!(script.contains("futhark opencl test-project.fut"));
        assert!(!script.contains("autotune"));
    }

    #[test]
    fn test_build_script_with_tuning() {
        let mut manifest = test_manifest();
        manifest.gpu.tuning = true;
        let script = generate_build_script(&manifest, Path::new("test-project.fut")).unwrap();
        assert!(script.contains("futhark autotune"));
    }

    #[test]
    fn test_build_script_checks_futhark_installed() {
        let manifest = test_manifest();
        let script = generate_build_script(&manifest, Path::new("test.fut")).unwrap();
        assert!(script.contains("command -v futhark"));
    }
}
