// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Futhark source code generator.
//
// Generates `.fut` files from validated kernel configurations. Each kernel
// becomes a Futhark `entry` function using the appropriate SOAC:
//
//   map       -> `entry blur (xs: []f32) : []f32 = map (\x -> x) xs`
//   reduce    -> `entry total (xs: []f64) : f64 = reduce (+) 0.0 xs`
//   scan      -> `entry prefix (xs: []f64) : []f64 = scan (+) 0.0 xs`
//   scatter   -> `entry write (dest: *[]f32) (is: []i64) (vs: []f32) = scatter dest is vs`
//   histogram -> `entry hist (xs: []u8) : []i64 = reduce_by_index (replicate 256 0) (+) 0 ...`
//
// The generated code is idiomatic Futhark and compiles with any backend.

use anyhow::Result;

use crate::abi::{FutharkType, KernelConfig, SOAC};
use crate::manifest::Manifest;

/// Generate a complete Futhark source file containing entry points for every
/// kernel in the manifest.
pub fn generate_futhark_source(manifest: &Manifest, kernels: &[KernelConfig]) -> Result<String> {
    let mut out = String::with_capacity(2048);

    // File header.
    out.push_str(&format!(
        "-- Auto-generated by futharkiser for project '{}'\n",
        manifest.project.name
    ));
    out.push_str("-- SPDX-License-Identifier: PMPL-1.0-or-later\n");
    out.push_str("-- Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>\n");
    out.push_str("--\n");
    out.push_str("-- DO NOT EDIT — regenerate with: futharkiser generate\n\n");

    // Generate each kernel entry point.
    for kernel in kernels {
        out.push_str(&generate_kernel_entry(kernel)?);
        out.push('\n');
    }

    Ok(out)
}

/// Generate a single Futhark `entry` function for one kernel.
fn generate_kernel_entry(kernel: &KernelConfig) -> Result<String> {
    let mut out = String::with_capacity(512);

    // Description comment.
    if !kernel.description.is_empty() {
        out.push_str(&format!("-- | {}\n", kernel.description));
    }

    match kernel.pattern {
        SOAC::Map => {
            out.push_str(&generate_map_entry(kernel));
        }
        SOAC::Reduce => {
            out.push_str(&generate_reduce_entry(kernel));
        }
        SOAC::Scan => {
            out.push_str(&generate_scan_entry(kernel));
        }
        SOAC::Scatter => {
            out.push_str(&generate_scatter_entry(kernel));
        }
        SOAC::Histogram => {
            out.push_str(&generate_histogram_entry(kernel));
        }
    }

    Ok(out)
}

/// Generate a `map` entry point.
///
/// ```futhark
/// entry blur (xs: []f32) : []f32 =
///   map (\x -> x) xs
/// ```
///
/// The identity lambda is a placeholder; users are expected to edit the
/// generated `.fut` file to insert their actual transformation logic.
fn generate_map_entry(kernel: &KernelConfig) -> String {
    let in_ty = kernel.input_type.futhark_name();
    let out_ty = kernel.output_type.futhark_name();
    format!(
        "entry {} (xs: []{}) : []{} =\n  map (\\x -> x) xs\n",
        kernel.name, in_ty, out_ty
    )
}

/// Generate a `reduce` entry point.
///
/// ```futhark
/// entry total (xs: []f64) : f64 =
///   reduce (+) 0.0 xs
/// ```
///
/// The operator and neutral element come from the kernel config.
fn generate_reduce_entry(kernel: &KernelConfig) -> String {
    let in_ty = kernel.input_type.futhark_name();
    let out_ty = kernel.output_type.futhark_name();
    let op = kernel.operator.as_deref().unwrap_or("+");
    let ne = kernel.output_type.neutral_element(op);

    // Wrap operator: single-char ops like "+" become "(+)", multi-char stay as-is.
    let op_expr = if op.len() <= 2 && !op.chars().any(|c| c.is_alphanumeric()) {
        format!("({})", op)
    } else {
        op.to_string()
    };

    format!(
        "entry {} (xs: []{}) : {} =\n  reduce {} {} xs\n",
        kernel.name, in_ty, out_ty, op_expr, ne
    )
}

/// Generate a `scan` (prefix sum/scan) entry point.
///
/// ```futhark
/// entry prefix_sum (xs: []f64) : []f64 =
///   scan (+) 0.0 xs
/// ```
fn generate_scan_entry(kernel: &KernelConfig) -> String {
    let in_ty = kernel.input_type.futhark_name();
    let out_ty = kernel.output_type.futhark_name();
    let op = kernel.operator.as_deref().unwrap_or("+");
    let ne = kernel.output_type.neutral_element(op);

    let op_expr = if op.len() <= 2 && !op.chars().any(|c| c.is_alphanumeric()) {
        format!("({})", op)
    } else {
        op.to_string()
    };

    format!(
        "entry {} (xs: []{}) : []{} =\n  scan {} {} xs\n",
        kernel.name, in_ty, out_ty, op_expr, ne
    )
}

/// Generate a `scatter` (indirect write) entry point.
///
/// ```futhark
/// entry write (dest: *[]f32) (is: []i64) (vs: []f32) : *[]f32 =
///   scatter dest is vs
/// ```
///
/// Scatter takes a destination array (unique/consumed), an index array, and a
/// values array. The destination must have the `*` uniqueness annotation.
fn generate_scatter_entry(kernel: &KernelConfig) -> String {
    let out_ty = kernel.output_type.futhark_name();
    let in_ty = kernel.input_type.futhark_name();
    format!(
        "entry {} (dest: *[]{}) (is: []i64) (vs: []{}) : *[]{} =\n  scatter dest is vs\n",
        kernel.name, out_ty, in_ty, out_ty
    )
}

/// Generate a `histogram` entry point using `reduce_by_index`.
///
/// ```futhark
/// entry histogram (xs: []u8) : []i64 =
///   let bins = replicate 256 0i64
///   in reduce_by_index bins (+) 0i64 (map i64.u8 xs) (replicate (length xs) 1i64)
/// ```
///
/// This counts occurrences of each value in `xs`, placing them into `bins`
/// buckets. The input values are cast to i64 indices.
fn generate_histogram_entry(kernel: &KernelConfig) -> String {
    let in_ty = kernel.input_type.futhark_name();
    let out_ty = kernel.output_type.futhark_name();
    let bins = kernel.bins.unwrap_or(256);
    let ne = kernel.output_type.neutral_element("+");

    // Build the index-casting expression. If the input type differs from i64,
    // we need an explicit cast so the indices are valid for reduce_by_index.
    let cast_expr = if kernel.input_type == FutharkType::I64 {
        "xs".to_string()
    } else {
        format!("(map i64.{} xs)", in_ty)
    };

    format!(
        "entry {} (xs: []{}) : []{} =\n  let bins = replicate {} {}{}\n  in reduce_by_index bins (+) {}{} {} (replicate (length xs) 1{})\n",
        kernel.name, in_ty, out_ty, bins, ne, out_ty, ne, out_ty, cast_expr, out_ty,
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_kernel(
        name: &str,
        pattern: SOAC,
        in_ty: FutharkType,
        out_ty: FutharkType,
    ) -> KernelConfig {
        KernelConfig {
            name: name.to_string(),
            pattern,
            input_type: in_ty,
            output_type: out_ty,
            description: String::new(),
            operator: None,
            bins: None,
        }
    }

    #[test]
    fn test_map_kernel_generation() {
        let kernel = make_kernel("blur", SOAC::Map, FutharkType::F32, FutharkType::F32);
        let code = generate_map_entry(&kernel);
        assert!(code.contains("entry blur"));
        assert!(code.contains("map (\\x -> x) xs"));
        assert!(code.contains("[]f32"));
    }

    #[test]
    fn test_reduce_kernel_generation() {
        let mut kernel = make_kernel("total", SOAC::Reduce, FutharkType::F64, FutharkType::F64);
        kernel.operator = Some("+".to_string());
        let code = generate_reduce_entry(&kernel);
        assert!(code.contains("entry total"));
        assert!(code.contains("reduce (+) 0.0 xs"));
        // Output type for reduce is scalar, not array.
        assert!(code.contains(": f64"));
    }

    #[test]
    fn test_scan_kernel_generation() {
        let mut kernel = make_kernel("prefix_sum", SOAC::Scan, FutharkType::F64, FutharkType::F64);
        kernel.operator = Some("+".to_string());
        let code = generate_scan_entry(&kernel);
        assert!(code.contains("entry prefix_sum"));
        assert!(code.contains("scan (+) 0.0 xs"));
        assert!(code.contains("[]f64"));
    }

    #[test]
    fn test_scatter_kernel_generation() {
        let kernel = make_kernel("write", SOAC::Scatter, FutharkType::F32, FutharkType::F32);
        let code = generate_scatter_entry(&kernel);
        assert!(code.contains("entry write"));
        assert!(code.contains("scatter dest is vs"));
        assert!(code.contains("*[]f32"));
    }

    #[test]
    fn test_histogram_kernel_generation() {
        let mut kernel = make_kernel("hist", SOAC::Histogram, FutharkType::U8, FutharkType::I64);
        kernel.bins = Some(256);
        let code = generate_histogram_entry(&kernel);
        assert!(code.contains("entry hist"));
        assert!(code.contains("reduce_by_index"));
        assert!(code.contains("replicate 256"));
        assert!(code.contains("map i64.u8 xs"));
    }

    #[test]
    fn test_full_source_generation() {
        let manifest = Manifest {
            project: crate::manifest::ProjectConfig {
                name: "test-project".to_string(),
            },
            kernels: vec![],
            gpu: crate::manifest::GpuConfig::default(),
        };
        let kernels = vec![make_kernel(
            "k1",
            SOAC::Map,
            FutharkType::F32,
            FutharkType::F32,
        )];
        let source = generate_futhark_source(&manifest, &kernels).expect("TODO: handle error");
        assert!(source.contains("Auto-generated by futharkiser"));
        assert!(source.contains("entry k1"));
        assert!(source.contains("PMPL-1.0-or-later"));
    }

    #[test]
    fn test_reduce_with_multiply_operator() {
        let mut kernel = make_kernel("product", SOAC::Reduce, FutharkType::I32, FutharkType::I32);
        kernel.operator = Some("*".to_string());
        let code = generate_reduce_entry(&kernel);
        assert!(code.contains("reduce (*) 1 xs"));
    }

    #[test]
    fn test_description_becomes_comment() {
        let mut kernel = make_kernel("blur", SOAC::Map, FutharkType::F32, FutharkType::F32);
        kernel.description = "Gaussian blur".to_string();
        let code = generate_kernel_entry(&kernel).expect("TODO: handle error");
        assert!(code.contains("-- | Gaussian blur"));
    }
}
